---
- name: Wait for instances to become reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for instances to become reachable
      wait_for_connection:
        delay: 10
        sleep: 10
        timeout: 120

- name: Collect DC/OS versions
  hosts: all
  tasks:
    - name: Collect DC/OS versions
      setup:

    # Some convoluted templating voodoo to create the dcos_master_list
    - name: "Create 'master_hosts_metadata' list from 'masters' group"
      # Loop over masters providing item.0 = loop_index and item.1 = hostname
      with_indexed_items: 
        - "{{ groups['masters'] | default([]) }}"
      vars:
        # Use a template to contain host related metadata
        master_host_template:
          host_fqdn: "{{ item.1 }}"
          # Lookup the IP address from the FQDN in the inventory 'masters' group.
          host_ip: "{{ lookup('dig', item.1) }}"
          host_id: "{{ item.0 + 1 }}"
      set_fact:
        # Create a list of host metadata
        master_hosts_metadata: "{{ ( master_hosts_metadata | default([]) ) + [master_host_template] }}"

    - name: "Create lists of master hosts for use in group_vars\\all\\dcos.yml"
      set_fact:
            dcos_master_ip_list:   "{{ ( dcos_master_ip_list   | default([]) ) + [item.1.host_ip] }}"
            dcos_master_fqdn_list: "{{ ( dcos_master_fqdn_list | default([]) ) + [item.1.host_fqdn] }}"
      with_indexed_items: 
        - "{{ master_hosts_metadata | default([]) }}"

- name: DC/OS Requirements
  hosts: all
  become: true
  tasks:
    - include_role:
        name: dcos_requirements
    - include_role:
        name: dcos_gpu

- name: "Setup and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: dcos_bootstrap

- name: "Setup and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: dcos_master

- name: "Setup and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: dcos_agent
