---

dcos_cli_bin_path: "/usr/local/bin"

  # This can be part of a load balanced cluster
marathon_service_instances: 1

docker_image_path: "mesosphere"
docker_image_name: "marathon-lb"
docker_image_tag: "v1.15.0"

docker_container_cpus: 2
docker_container_disk: 0
docker_container_mem: 1024
docker_container_gpus: 0

marathon_lb_deploy_config:
  "cpus": "{{ docker_container_cpus }}"
  "disk": "{{ docker_container_disk }}"
  "mem": "{{ docker_container_mem }}"
  "gpus": "{{ docker_container_gpus }}"
  "env": 
    "HAPROXY_GLOBAL_DEFAULT_OPTIONS": "redispatch,http-server-close,dontlognull"
    "HAPROXY_SYSCTL_PARAMS": "net.ipv4.tcp_tw_reuse=1 net.ipv4.tcp_fin_timeout=30 net.ipv4.tcp_max_syn_backlog=10240 net.ipv4.tcp_max_tw_buckets=400000 net.ipv4.tcp_max_orphans=60000 net.core.somaxconn=10000"
  "id": "/{{ docker_image_name }}"
  # Only run this on Mesos Public Agents
  "acceptedResourceRoles": 
    - "slave_public"
  # Selection constraints for Mesos Public Agent attributes
  "constraints": []
  # Parameters to 'run' command
  "args": [
    "sse",
    "-m",
    "http://marathon.mesos:8080",
    "--health-check",
    "--haproxy-map",
    "--max-reload-retries",
    "10",
    "--reload-interval",
    "10",
    "--ssl-certs",
    "/host_pki/certs/star_tmvse_com.bundle.haproxy.crt.pem",
    "--group",
    "external"
  ]
  "backoffFactor": 1.15
  "backoffSeconds": 1
  "container": {
    - "type": "DOCKER"
      # Mount the common certificates from the host
      "volumes": 
        - "containerPath": "/host_pki"
          "hostPath": "/etc/pki/tls"
          "mode": "RO"
      "docker":
        "image": "{{ docker_image_path }}/{{ docker_image_name }}:{{ docker_image_tag }}"
        "forcePullImage": false
        "privileged": true
        "parameters": []
  "healthChecks": 
    - "gracePeriodSeconds": 60
      "intervalSeconds": 5
      "maxConsecutiveFailures": 2
      "portIndex": 2
      "timeoutSeconds": 2
      "delaySeconds": 15
      "protocol": "MESOS_HTTP"
      "path": "/_haproxy_health_check"
      "ipProtocol": "IPv4"
  "instances": "{{ marathon_service_instances }}"
  "maxLaunchDelaySeconds": 300
  "networks": 
    - "mode": "host"
  "portDefinitions":
    - "protocol": "tcp"
      "port": 80
    - "protocol": "tcp"
      "port": 443
    - "protocol": "tcp"
      "port": 9090
    - "protocol": "tcp"
      "port": 9091
    - "protocol": "tcp"
      "port": 10000
    - "protocol": "tcp"
      "port": 10001
    - "protocol": "tcp"
      "port": 10002
    - "protocol": "tcp"
      "port": 10003
    - "protocol": "tcp"
      "port": 10004
    - "protocol": "tcp"
      "port": 10005
    - "protocol": "tcp"
      "port": 10006
    - "protocol": "tcp"
      "port": 10007
    - "protocol": "tcp"
      "port": 10008
    - "protocol": "tcp"
      "port": 10009
    - "protocol": "tcp"
      "port": 10010
    - "protocol": "tcp"
      "port": 10011
    - "protocol": "tcp"
      "port": 10012
    - "protocol": "tcp"
      "port": 10013
    - "protocol": "tcp"
      "port": 10014
    - "protocol": "tcp"
      "port": 10015
    - "protocol": "tcp"
      "port": 10016
    - "protocol": "tcp"
      "port": 10017
    - "protocol": "tcp"
      "port": 10018
    - "protocol": "tcp"
      "port": 10019
    - "protocol": "tcp"
      "port": 10020
    - "protocol": "tcp"
      "port": 10021
    - "protocol": "tcp"
      "port": 10022
    - "protocol": "tcp"
      "port": 10023
    - "protocol": "tcp"
      "port": 10024
    - "protocol": "tcp"
      "port": 10025
    - "protocol": "tcp"
      "port": 10026
    - "protocol": "tcp"
      "port": 10027
    - "protocol": "tcp"
      "port": 10028
    - "protocol": "tcp"
      "port": 10029
    - "protocol": "tcp"
      "port": 10030
    - "protocol": "tcp"
      "port": 10031
    - "protocol": "tcp"
      "port": 10032
    - "protocol": "tcp"
      "port": 10033
    - "protocol": "tcp"
      "port": 10034
    - "protocol": "tcp"
      "port": 10035
    - "protocol": "tcp"
      "port": 10036
    - "protocol": "tcp"
      "port": 10037
    - "protocol": "tcp"
      "port": 10038
    - "protocol": "tcp"
      "port": 10039
    - "protocol": "tcp"
      "port": 10040
    - "protocol": "tcp"
      "port": 10041
    - "protocol": "tcp"
      "port": 10042
    - "protocol": "tcp"
      "port": 10043
    - "protocol": "tcp"
      "port": 10044
    - "protocol": "tcp"
      "port": 10045
    - "protocol": "tcp"
      "port": 10046
    - "protocol": "tcp"
      "port": 10047
    - "protocol": "tcp"
      "port": 10048
    - "protocol": "tcp"
      "port": 10049
    - "protocol": "tcp"
      "port": 10050
    - "protocol": "tcp"
      "port": 10051
    - "protocol": "tcp"
      "port": 10052
    - "protocol": "tcp"
      "port": 10053
    - "protocol": "tcp"
      "port": 10054
    - "protocol": "tcp"
      "port": 10055
    - "protocol": "tcp"
      "port": 10056
    - "protocol": "tcp"
      "port": 10057
    - "protocol": "tcp"
      "port": 10058
    - "protocol": "tcp"
      "port": 10059
    - "protocol": "tcp"
      "port": 10060
    - "protocol": "tcp"
      "port": 10061
    - "protocol": "tcp"
      "port": 10062
    - "protocol": "tcp"
      "port": 10063
    - "protocol": "tcp"
      "port": 10064
    - "protocol": "tcp"
      "port": 10065
    - "protocol": "tcp"
      "port": 10066
    - "protocol": "tcp"
      "port": 10067
    - "protocol": "tcp"
      "port": 10068
    - "protocol": "tcp"
      "port": 10069
    - "protocol": "tcp"
      "port": 10070
    - "protocol": "tcp"
      "port": 10071
    - "protocol": "tcp"
      "port": 10072
    - "protocol": "tcp"
      "port": 10073
    - "protocol": "tcp"
      "port": 10074
    - "protocol": "tcp"
      "port": 10075
    - "protocol": "tcp"
      "port": 10076
    - "protocol": "tcp"
      "port": 10077
    - "protocol": "tcp"
      "port": 10078
    - "protocol": "tcp"
      "port": 10079
    - "protocol": "tcp"
      "port": 10080
    - "protocol": "tcp"
      "port": 10081
    - "protocol": "tcp"
      "port": 10082
    - "protocol": "tcp"
      "port": 10083
    - "protocol": "tcp"
      "port": 10084
    - "protocol": "tcp"
      "port": 10085
    - "protocol": "tcp"
      "port": 10086
    - "protocol": "tcp"
      "port": 10087
    - "protocol": "tcp"
      "port": 10088
    - "protocol": "tcp"
      "port": 10089
    - "protocol": "tcp"
      "port": 10090
    - "protocol": "tcp"
      "port": 10091
    - "protocol": "tcp"
      "port": 10092
    - "protocol": "tcp"
      "port": 10093
    - "protocol": "tcp"
      "port": 10094
    - "protocol": "tcp"
      "port": 10095
    - "protocol": "tcp"
      "port": 10096
    - "protocol": "tcp"
      "port": 10097
    - "protocol": "tcp"
      "port": 10098
    - "protocol": "tcp"
      "port": 10099
    - "protocol": "tcp"
      "port": 10100
  "requirePorts": true
  "upgradeStrategy": 
    "maximumOverCapacity": 0.2
    "minimumHealthCapacity": 0.5
  "killSelection": "YOUNGEST_FIRST"
  "unreachableStrategy":
    "inactiveAfterSeconds": 0
    "expungeAfterSeconds": 0
  "role": "slave_public"
  # Files to load into sandbox
  "fetch": []
